#
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <norwd@noreply.codeberg.org>
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>
# SPDX-License-Identifier: LicenseRef-Hippocratic-3.0-CL-ECO-LAW-MIL-SV
#

---

name: "Run EditorConfig Checker"

on:
  push:
  schedule:
    - cron: '33 9 * * 2'

jobs:

  editorconfig-checker:
    name: "Run EditorConfig Checker"
    runs-on: codeberg-tiny
    timeout-minutes: 5
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        run: curl -fsSLo- "${TARBALL}" | tar xz
        env:
          TARBALL: https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.7.0/editorconfig-checker-linux-amd64.tar.gz

      - name: "Run EditorConfig Checker"
        run: ./editorconfig-checker

...
