filetype plugin on
filetype indent on

syntax enable

set nocompatible
set noerrorbells
set novisualbell
set belloff=all
set ruler
set ignorecase
set smartcase
set hlsearch
set nobackup
set nowb
set noswapfile
set noshowmatch
set mouse=a
set viminfofile=NONE
set number
"set relativenumber
set incsearch
set hlsearch
set backspace=indent,eol,start
set wildmenu
