filetype plugin on
filetype indent on

syntax enable

if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME  = $HOME."/.cache"       | endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME."/.config"      | endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME   = $HOME."/.local/share" | endif
if empty($XDG_STATE_HOME)  | let $XDG_STATE_HOME  = $HOME."/.local/state" | endif

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
set nocompatible
set noerrorbells
set novisualbell
set belloff=all
set ruler
set ignorecase
set smartcase
set hlsearch
set nobackup
set nowb
set noswapfile
set noshowmatch
set mouse=a
set viminfofile=NONE
set number
set incsearch
set hlsearch
set backspace=indent,eol,start
set wildmenu

