#!/bin/sh

for profile in "${XDG_CONFIG_HOME:-${HOME}/.config}/profile.d/"*.sh # zshellcheck disable=ZC1040
do
	if [ -r "${profile}" ]
	then
		# shellcheck source=/dev/null
		. "${profile}"
	fi
done

unset profile
