#!/bin/sh
# shellcheck source=/dev/null

#
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <norwd@noreply.codeberg.org>
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>
# SPDX-License-Identifier: LicenseRef-Hippocratic-3.0-CL-ECO-LAW-MIL-SV
#

for profile in "${XDG_CONFIG_HOME:-${HOME}/.config}/profile.d/"*.sh # zshellcheck disable=ZC1040
do [ -r "${profile}" ] && . "${profile}"
done
unset profile
