---

name: "Run ActionLint"
run-name: "Run ActionLint"
permissions: {}
on: push

jobs:

  actionlint:
    name: "Run ActionLint"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Run ActionLint"
        uses: norwd/actionlint@main
