name: "Run Benchmark"
run-name: "Run Benchmark"
on: push

jobs:

  benchmark:
    name: "Run Benchmark"
    runs-on: macos-latest
    strategy:
      matrix:
        ref:
          - main
          - ${{ github.sha }}

    steps:

      - name: "Clone"
        run: git clone --bare ${{ github.server_url }}/${{ github.repository }} ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout --force "${REF}"
        env:
          REF: ${{ matrix.ref }}

      - name: "Install Hyperfine"
        run: brew install hyperfine

      - name: "Run Benchmarks"
        run: >-
          hyperfine
          --warmup 25
          --min-runs 50
          --max-runs 100
          --time-unit millisecond
          --export-json benchmarks.json
          --shell 'zsh -i -l'
          --setup 'sleep 0.25'
          --command-name 'Source Zshrc'           'source ~/.zshrc'
          --command-name 'Source Zsh Profile'     'source ~/.zprofile'
          --command-name 'Source Login Profile'   'source ~/.config/profile'
          --command-name 'Startup and Exit Zsh'   'zsh -i -l -c exit'

      - name: "Upload Benchmarks"
        uses: actions/upload-artifact@v7
        with:
          name: benchmarks-${{ matrix.ref }}
          path: benchmarks.json
          if-no-files-found: error
