name: "Run Benchmark"
run-name: "Run Benchmark"
on: push

jobs:

  benchmark:
    name: "Run Benchmark"
    runs-on: macos-latest
    strategy:
      matrix:
        ref:
          - main
          - ${{ github.sha }}

    steps:

      - name: "Clone"
        run: git clone --bare ${{ github.server_url }}/${{ github.repository }} ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout --force "${REF}"
        env:
          REF: ${{ matrix.ref }}

      - name: "Install Hyperfine"
        run: brew install hyperfine

      - name: "Run Benchmarks"
        run: >-
          hyperfine
          --warmup 5
          --min-runs 10
          --max-runs 100
          --time-unit millisecond
          --export-json raw-benchmarks.json
          --shell 'zsh -i -l'
          --command-name 'Source Zshrc'           'source ~/.zshrc'
          --command-name 'Source Zsh Profile'     'source ~/.zprofile'
          --command-name 'Source Login Profile'   'source ~/.config/profile'
          --command-name 'Startup and Exit Zsh'   'zsh -i -l -c exit'

      - name: "Process Benchmark"
        run: jq "${JQ_QUERY}" raw-benchmarks.json | tee -a benchmark-data-${{ matrix.ref }}.json
        env:
          JQ_QUERY: |
            [
              .results[] |
              [
                {
                  name: "\(.command) - Mean Time",
                  unit: "Seconds",
                  value: .mean,
                },
                {
                  name: "\(.command) - Median Time",
                  unit: "Seconds",
                  value: .median,
                },
                {
                  name: "\(.command) - User Time",
                  unit: "Seconds",
                  value: .user,
                },
                {
                  name: "\(.command) - System Time",
                  unit: "Seconds",
                  value: .system,
                },
                {
                  name: "\(.command) - Min Time",
                  unit: "Seconds",
                  value: .min,
                },
                {
                  name: "\(.command) - Max Time",
                  unit: "Seconds",
                  value: .max,
                }
              ][]
            ]

      - name: "Upload Benchmark Data"
        uses: actions/upload-artifact@v7
        with:
          path: benchmark-data-${{ matrix.ref }}.json
          archive: false
          if-no-files-found: error

  check-benchmarks:
    name: "Check Benchmark Results"
    needs: benchmark
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: "Download Benchmark Data - Mainline"
        uses: actions/download-artifact@v8
        with:
          name: benchmark-data-main.json

      - name: "Download Benchmark Data - Current Changes"
        uses: actions/download-artifact@v8
        with:
          name: benchmark-data-${{ github.sha }}.json

      - run: cat benchmark-data-${{ github.sha }}.json benchmark-data-main.json

      - name: "Compare Benchmark Results"
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: benchmark-data-${{ github.sha }}.json
          external-data-json-path: benchmark-data-main.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          summary-always: true
          fail-on-alert: true
