name: "Benchmark"
run-name: "Benchmark"
on: push

permissions:
  contents: write

jobs:

  benchmark:
    name: "Performance regression check"
    runs-on: macos-latest
    steps:

      - name: "Clone"
        run: git clone --bare ${{ github.server_url }}/${{ github.repository }} ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - name: "Install Zbench"
        working-directory: /usr/local/bin
        run: curl -sSLO "${URL}" && chmod +x zsh-bench
        env:
          URL: https://raw.githubusercontent.com/romkatv/zsh-bench/refs/heads/master/zsh-bench

      - name: "Run Benchmark"
        shell: zsh -i -l {0}
        run: zsh-bench | tee -a output.txt
        env:
          JSON: |
            [
              {
                "name": "My Custom Smaller Is Better Benchmark - CPU Load",
                "unit": "Percent",
                "value": 50
              },
              {
                "name": "My Custom Smaller Is Better Benchmark - Memory Used",
                "unit": "Megabytes",
                "value": 100,
                "range": "3",
                "extra": "Value for Tooltip: 25\nOptional Num #2: 100\nAnything Else!"
              }
            ]

      - name: "Download previous benchmark data"
        uses: actions/cache@v5
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: "Store benchmark result"
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          summary-always: true
          fail-on-alert: true
