---

name: "Run EditorConfig Checker"
run-name: "Run EditorConfig Checker"
permissions: {}
on: push

jobs:

  editorconfig-checker:
    name: "Run EditorConfig Checker"
    runs-on: ubuntu-slim
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        uses: editorconfig-checker/action-editorconfig-checker@v2.2.0

      - name: "Run EditorConfig Checker"
        run: editorconfig-checker

...
