#
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <norwd@noreply.codeberg.org>
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>
# SPDX-License-Identifier: Hippocratic-3.0-CL-ECO-LAW-MIL-SV
#

---

name: "Run EditorConfig Checker"
run-name: "Run EditorConfig Checker"
permissions: {}

on:
  schedule: [ cron: '33 9 * * 2' ]
  push:

jobs:

  editorconfig-checker:
    name: "Run EditorConfig Checker"
    runs-on: ubuntu-slim
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        uses: editorconfig-checker/action-editorconfig-checker@v2.2.0

      - name: "Run EditorConfig Checker"
        run: editorconfig-checker

...
