#
# Copyright (C) 2026 Y. Meyer-Norwood
# This file is distributed under the Hippocratic License 3.0 (HL3-CL-ECO-LAW-MIL-SV)
#

---

name: "Run EditorConfig Checker"
run-name: "Run EditorConfig Checker"
permissions: {}

on:
  schedule: [ cron: '33 9 * * 2' ]
  push:

jobs:

  editorconfig-checker:
    name: "Run EditorConfig Checker"
    runs-on: ubuntu-slim
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        uses: editorconfig-checker/action-editorconfig-checker@v2.2.0

      - name: "Run EditorConfig Checker"
        run: editorconfig-checker

...
