---

name: "Lint"
run-name: "Lint"
on: push
permissions: {}

jobs:

  detect-changes:
    name: "Detect if there are any changes since the last lint"
    runs-on: ubuntu-slim
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - id: detect-changes
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('**/*') }}
          path: |
            **/*

      - id: detect-changes-py
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('**/*.py') }}
          path: |
            **/*.py

      - id: detect-changes-sh
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('.profile', '.config/profile', '**/*.sh*') }}
          path: |
            .profile
            .config/profile
            **/*.sh*

      - id: detect-changes-bash
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('.profile', '.config/profile', '**/*.bash*') }}
          path: |
            .profile
            .config/profile
            **/*.bash*

      - id: detect-changes-ksh
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('.profile', '.config/profile', '**/*.ksh*') }}
          path: |
            .profile
            .config/profile
            **/*.ksh*

      - id: detect-changes-zsh
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('.profile', '.config/profile', '**/*.zsh', '**/*.zlog*', '**/*.zprofile') }}
          path: |
            .profile
            .config/profile
            **/*.zsh*
            **/*.zlog*
            **/*.zprofile

    outputs:
      changes-detected: ${{ steps.detect-changes.outputs.cache-hit != 'true' }}
      changes-detected-py: ${{ steps.detect-changes-py.outputs.cache-hit != 'true' }}
      changes-detected-sh: ${{ steps.detect-changes-sh.outputs.cache-hit != 'true' }}
      changes-detected-bash: ${{ steps.detect-changes-bash.outputs.cache-hit != 'true' }}
      changes-detected-ksh: ${{ steps.detect-changes-ksh.outputs.cache-hit != 'true' }}
      changes-detected-zsh: ${{ steps.detect-changes-zsh.outputs.cache-hit != 'true' }}
      changes-detected-any-shell: >-
        ${{
          steps.detect-changes-sh.outputs.cache-hit != 'true' ||
          steps.detect-changes-bash.outputs.cache-hit != 'true' ||
          steps.detect-changes-ksh.outputs.cache-hit != 'true' ||
          steps.detect-changes-zsh.outputs.cache-hit != 'true' ||
          false
        }}

  lint-shellcheck:
    if: needs.detect-changes.outputs.changes-detected-any-shell == 'true'
    needs: detect-changes
    name: "Lint ShellCheck ${{ matrix.shell }} (${{ matrix.severity }})"
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        shell: [ sh, ksh, bash ]
        severity:
          - style
          - info
          - warning
          - error

    steps:

      - if: needs.detect-changes.outputs[format('changes-detected-{0}', matrix.shell)] == 'true'
        name: "Checkout"
        uses: actions/checkout@v6

      - if: needs.detect-changes.outputs[format('changes-detected-{0}', matrix.shell)] == 'true'
        name: "Install"
        run: brew install shellcheck

      - if: needs.detect-changes.outputs[format('changes-detected-{0}', matrix.shell)] == 'true'
        name: "ShellCheck"
        run: >
          shellcheck
          --severity ${{ matrix.severity }}
          --shell=${{ matrix.shell }}
          --rcfile .config/shellcheckrc
          .config/profile
          $(find . -type f -name "*.sh")

  lint-shellcheck-zsh:
    if: needs.detect-changes.outputs.changes-detected-zsh == 'true'
    needs: detect-changes
    name: "Lint ShellCheck zsh as ${{ matrix.shell }} (${{ matrix.severity }})"
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        shell: [ ksh, bash ] # zsh isn't supported directly, but is semi-compatible with both ksh and bash
        severity:
          - style
          - info
          - warning
          - error

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install"
        run: brew install shellcheck

      - name: "ShellCheck"
        run: >
          shellcheck
          --severity ${{ matrix.severity }}
          --shell=${{ matrix.shell }}
          --rcfile .config/shellcheckrc
          $(find . -type f -name "*.zsh")
          $(find . -type f -name "*.zshenv")
          $(find . -type f -name "*.zprofile")
          $(find . -type f -name "*.zshrc")
          $(find . -type f -name "*.zlogin")
          $(find . -type f -name "*.zlogout")

  lint-zshellcheck:
    if: needs.detect-changes.outputs.changes-detected-zsh == 'true'
    needs:
      - detect-changes
      - lint-shellcheck-zsh

    name: "Lint ZShellCheck zsh (${{ matrix.severity }})"
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        severity:
          - style
          - info
          - warning
          - error

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Fake go.mod"
        run: touch go.mod

      - name: "Setup"
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: "Install"
        run: go install github.com/afadesigns/zshellcheck/cmd/zshellcheck@latest

      - name: "ZShellCheck"
        run: >
          zshellcheck
          --severity ${{ matrix.severity }}
          $(find . -type f -name "*.zsh")
          $(find . -type f -name "*.zshenv")
          $(find . -type f -name "*.zprofile")
          $(find . -type f -name "*.zshrc")
          $(find . -type f -name "*.zlogin")
          $(find . -type f -name "*.zlogout")

  scan-shellcheck:
    if: needs.detect-changes.outputs.changes-detected-any-shell == 'true'
    needs:
      - detect-changes
      - lint-shellcheck
      - lint-shellcheck-zsh

    name: "Scan Shellcheck ${{ matrix.shell }} (${{ matrix.severity }})"
    runs-on: macos-latest

    permissions:
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        shell: [ sh, ksh, bash ]
        severity:
          - style
          - info
          - warning
          - error

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Fake requirements.txt"
        run: touch requirements.txt

      - if: needs.detect-changes.outputs[format('changes-detected-{0}', matrix.shell)] == 'true'
        name: "ShellCheck with SARIF"
        uses: reactive-firewall/shellcheck-scan@v2
        with:
          severity: ${{ matrix.severity }}
          shell-format: ${{ matrix.shell }}
          publish-artifacts: false
          match: >
            .config/profile
            **/*.{sh,bash,ksh}

  editorconfig:
    if: needs.detect-changes.outputs.changes-detected == 'true'
    needs: detect-changes
    name: "Check files match editorconfig"
    runs-on: ubuntu-slim
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        uses: editorconfig-checker/action-editorconfig-checker@v2.2.0

      - name: "Check editorconfig"
        run: editorconfig-checker

  lint-python:
    if: needs.detect-changes.outputs.changes-detected-py == 'true'
    needs: detect-changes
    name: "Lint Python"
    runs-on: ubuntu-slim
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - id: list-python-files
        name: "Find Python files"
        run: echo "paths=$(find . -type f -name '*.py' | xargs)" | tee -a "${GITHUB_OUTPUT}"

      - name: "Lint Python with Ruff"
        uses: astral-sh/ruff-action@v3
        with:
          src: ${{ steps.list-python-files.outputs.paths }}
