---

name: "Lint"
run-name: "Lint"
on: push
permissions: {}

jobs:

  lint-shellcheck:
    name: "Lint Shellcheck"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install"
        run: wget --quiet --output-document - "${RELEASE_URL}" | sudo tar --extract --xz --verbose --directory=/usr/bin/ --transform='s|.*shellcheck-latest/||' shellcheck-latest/shellcheck
        env:
          RELEASE_URL: https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz

      - if: runner.debug == 1
        name: "Debug"
        run: shellcheck --version

      - name: "ShellCheck"
        run: shellcheck --rcfile .config/shellcheckrc $(find . -type f -name "*.sh") .config/profile

  scan-shellcheck-scan:
    name: "Scan Shellcheck"
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # required for uploading SARIF results

    steps:

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "ShellCheck with SARIF"
        uses: reactive-firewall/shellcheck-scan@v1
