---

name: "Lint"
run-name: "Lint"
on: push
permissions: {}

jobs:

  lint-shellcheck:
    name: "Lint ShellCheck ${{ matrix.shell }} (${{ matrix.severity }})"
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        shell: [ sh, ksh, bash, dash ]
        severity:
          - style
          - info
          - warning
          - error

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - id: cache
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('.config/profile', '**/*.sh') }}
          path: |
            .config/profile
            **/*.sh

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "Install"
        run: brew install shellcheck

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "ShellCheck"
        run: >
          shellcheck
          --severity ${{ matrix.severity }}
          --shell=${{ matrix.shell }}
          --rcfile .config/shellcheckrc
          .config/profile
          $(find . -type f -name "*.sh")

  lint-shellcheck-zsh:
    name: "Lint ShellCheck zsh as ${{ matrix.shell }} (${{ matrix.severity }})"
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        shell: [ ksh, bash ] # zsh isn't supported directly, but is semi-compatible with both ksh and bash
        severity:
          - style
          - info
          - warning
          - error

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - id: cache
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('**/*.zsh', '**/*.zshenv', '**/*.zprofile', '**/*.zshrc', '**/*.zlogin', '**/*.zlogout') }}
          path: |
            **/*.zsh
            **/*.zshenv
            **/*.zprofile
            **/*.zshrc
            **/*.zlogin
            **/*.zlogout

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "Install"
        run: brew install shellcheck

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "ShellCheck"
        run: >
          shellcheck
          --severity ${{ matrix.severity }}
          --shell=${{ matrix.shell }}
          --rcfile .config/shellcheckrc
          $(find . -type f -name "*.zsh")
          $(find . -type f -name "*.zshenv")
          $(find . -type f -name "*.zprofile")
          $(find . -type f -name "*.zshrc")
          $(find . -type f -name "*.zlogin")
          $(find . -type f -name "*.zlogout")

  lint-zshellcheck:
    name: "Lint ZShellCheck zsh (${{ matrix.severity }})"
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        severity:
          - style
          - info
          - warning
          - error

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Fake go.mod"
        run: touch go.mod

      - id: cache
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('**/*.zsh', '**/*.zshenv', '**/*.zprofile', '**/*.zshrc', '**/*.zlogin', '**/*.zlogout') }}
          path: |
            **/*.zsh
            **/*.zshenv
            **/*.zprofile
            **/*.zshrc
            **/*.zlogin
            **/*.zlogout

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "Setup"
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "Install"
        run: go install github.com/afadesigns/zshellcheck/cmd/zshellcheck@latest

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "ZShellCheck"
        run: >
          zshellcheck
          --severity ${{ matrix.severity }}
          $(find . -type f -name "*.zsh")
          $(find . -type f -name "*.zshenv")
          $(find . -type f -name "*.zprofile")
          $(find . -type f -name "*.zshrc")
          $(find . -type f -name "*.zlogin")
          $(find . -type f -name "*.zlogout")

  scan-shellcheck:
    name: "Scan Shellcheck ${{ matrix.shell }} (${{ matrix.severity }})"
    runs-on: macos-latest

    permissions:
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        shell: [ sh, ksh, bash, dash ]
        severity:
          - style
          - info
          - warning
          - error

    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Fake requirements.txt"
        run: touch requirements.txt

      - id: cache
        name: "Cache"
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ join(matrix.*, '-') }}-${{ hashFiles('.config/profile', '**/*.sh', '**/*.bash', '**/*.ksh') }}
          path: |
            .config/profile
            **/*.sh
            **/*.bash
            **/*.ksh

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "ShellCheck with SARIF"
        uses: reactive-firewall/shellcheck-scan@v2
        with:
          severity: ${{ matrix.severity }}
          shell-format: ${{ matrix.shell }}
          publish-artifacts: false
          match: >
            .config/profile
            **/*.{sh,bash,ksh}

  editorconfig:
    name: "Check files match editorconfig"
    runs-on: ubuntu-slim
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        uses: editorconfig-checker/action-editorconfig-checker@v2.2.0

      - name: "Check editorconfig"
        run: editorconfig-checker
