#
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <norwd@noreply.codeberg.org>
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>
# SPDX-License-Identifier: LicenseRef-Hippocratic-3.0-CL-ECO-LAW-MIL-SV
#

---

name: "Push to Mirror"
run-name: "Push to Mirror"
permissions: {}

on:
  push:
    # paths: [.github/workflows/mirror.yml] # Comment out before merging
    branches: [main] # Uncomment before merging

defaults:
  run:
    shell: bash

jobs:
  push-to-mirror:
    name: "Push to Mirror"
    runs-on: ubuntu-latest
    steps:

        - name: "Configure SSH"
          run: |
            mkdir -p ~/.ssh/
            echo "${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            echo "${{ secrets.CODEBERG_SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
            chmod 700 ~/.ssh/
            chmod 600 ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519.pub
            ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts  
            ssh-keyscan -t ed25519 codeberg.org >> ~/.ssh/known_hosts  

        - name: "Clone Source"
          run: git clone --bare git@github.com:${{ github.repository }}.git repo

        - working-directory: repo
          name: "Push to Mirror"
          run: git push --mirror ssh://git@codeberg.org/${{ github.repository }}.git
