#
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <norwd@noreply.codeberg.org>
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>
# SPDX-License-Identifier: LicenseRef-Hippocratic-3.0-CL-ECO-LAW-MIL-SV
#

---

name: "Run Reuse"
run-name: "Run Reuse"
permissions: {}
on: push

defaults:
  run:
    shell: bash

jobs:

  reuse:
    name: "Run Reuse"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install"
        run: sudo apt install reuse

      - id: reuse-lint
        name: "Lint"
        run: reuse lint | tee -a "${GITHUB_STEP_SUMMARY}"
