---

name: "Run Ruff"
run-name: "Run Ruff"
permissions: {}

on:
  schedule: [ cron: '33 9 * * 2' ]
  push:
    paths:
      - '.github/workflows/ruff.yml'
      - '**/*.py'

jobs:

  ruff:
    name: "Run Ruff"
    runs-on: ubuntu-slim
    steps:

      - name: "Setup"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: "Install"
        run: gem install github-linguist

      - run: which github-linguist

      - name: "Checkout"
        uses: actions/checkout@v6

      - id: list-python-files
        name: "Find Python files"
        run: echo "paths=$(find . -type f -name '*.py' | xargs)" | tee -a "${GITHUB_OUTPUT}"

      - name: "Run Ruff"
        uses: astral-sh/ruff-action@v3
        with:
          src: ${{ steps.list-python-files.outputs.paths }}
