---

name: "Run Ruff"
run-name: "Run Ruff"
permissions: {}

on:
  schedule: [ cron: '33 9 * * 2' ]
  push:
    paths:
      - '.github/workflows/ruff.yml'
      - '**/*.py'

jobs:

  ruff:
    name: "Run Ruff"
    runs-on: ubuntu-latest
    steps:

      - name: "Add PATH"
        run: echo "${HOME}/.local/bin" | tee -a "${GITHUB_PATH}"

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: "Cache"
        id: cache-github-linguist
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-gem-install-github-linguist
          path: ~/.local/bin/github-linguist

      - if: steps.cache-github-linguist.outputs.cache-hit != 'true'
        name: "Install"
        run: sudo gem install github-linguist --bindir "${HOME}/.local/bin"

      - id: linguist
        name: "List Files by Language"
        run: github-linguist --breakdown --strategies --json . | jq --raw-output "${JQ_QUERY}" | sed '/^$/d' | tee -a "${GITHUB_OUTPUT}"
        env:
          JQ_QUERY: |
            to_entries[] |
            .key |= (ascii_downcase | gsub("\\s"; "-"; "g")) |
            .value |= (.files) |
            "
            \(.key)-json=\(.value)
            \(.key)-files=\(.value | join(" "))
            "

      - name: "Run Ruff"
        uses: astral-sh/ruff-action@v3
        with:
          src: ${{ steps.linguist.outputs.python-files }}
