#
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <norwd@noreply.codeberg.org>
# SPDX-FileCopyrightText: 2026 Y. Meyer-Norwood <106889957+norwd@users.noreply.github.com>
# SPDX-License-Identifier: Hippocratic-3.0-CL-ECO-LAW-MIL-SV
#

---

name: "Run TruffleHog"
run-name: "Run TruffleHog"
permissions: {}
on: push

jobs:
  trufflehog:
    name: "Run TruffleHog"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Run TruffleHog"
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
