---

name: "Validate"
run-name: "Validate"
on: push
permissions: {}

jobs:

  validate-installation:
    name: "Validate Installation"
    runs-on: macos-latest
    steps:

      - if: runner.debug == 1
        name: "Show zsh version"
        run: zsh --version

      - name: "Clone"
        run: git clone --bare https://github.com/norwd/etc ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - name: "Validate"
        run: |
          test -f ~/.editorconfig
          test -d ~/.cache
          test -d ~/.config
          test -f ~/.config/vim/vimrc
          test -d ~/.local/bin
          test -d ~/.local/share
          test -d ~/.local/state

  validate-shell-environment:
    name: "Validate Shell Environment"
    runs-on: macos-latest
    steps:

      - name: "Clone"
        run: git clone --bare https://github.com/norwd/etc ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - name: "Validate"
        shell: bash --posix -i -l {0}
        run: |
          . ~/.config/profile # Note: this would need to go in ~/.profile or ~/.bash_profile

          errfile="${{ runner.temp }}/errfile.txt"

          echo "::group::Validate .config/profile.d/005-environment.sh"
          if [ -z "${VISUAL+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/005-environment.sh,line=$(awk '/VISUAL=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1),title=ERROR::VISUAL is not set but should be set to vim in .config/profile.d/005-environment.sh"
          elif [ ! "${VISUAL}" == "vim" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/005-environment.sh,line=$(awk '/VISUAL=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1),title=ERROR::VISUAL is set to \"${VISUAL}\" but should be set to vim in .config/profile.d/005-environment.sh"
          else
            echo "::notice file=.config/profile.d/005-environment.sh,line=$(awk '/VISUAL=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1)::VISUAL is set correctly in .config/profile.d/005-environment.sh"
          fi

          if [ -z "${EDITOR+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/005-environment.sh,line=$(awk '/EDITOR=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1),title=ERROR::EDITOR is not set but should be set to vim in .config/profile.d/005-environment.sh"
          elif [ ! "${EDITOR}" == "vim" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/005-environment.sh,line=$(awk '/EDITOR=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1),title=ERROR::EDITOR is set to \"${EDITOR}\" but should be set to vim in .config/profile.d/005-environment.sh"
          else
            echo "::notice file=.config/profile.d/005-environment.sh,line=$(awk '/EDITOR=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1)::EDITOR is set correctly in .config/profile.d/005-environment.sh"
          fi
          echo "::endgroup::"

          echo "::group::Validate .config/profile.d/010-xdg-base-dirs.sh"
          if [ -z "${XDG_CONFIG_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CONFIG_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_CONFIG_HOME is not set but should be set to ~/.config in .config/profile.d/010-xdg-base-dirs.sh"
          elif [ ! "${XDG_CONFIG_HOME}" == "${HOME}/.config" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CONFIG_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_CONFIG_HOME is set to \"${XDG_CONFIG_HOME}\" but should be set to ~/.config in .config/profile.d/010-xdg-base-dirs.sh"
          else
            echo "::notice file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CONFIG_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1)::XDG_CONFIG_HOME is set correctly in .config/profile.d/010-xdg-base-dirs.sh"
          fi

          if [ -z "${XDG_CACHE_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CACHE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_CACHE_HOME is not set but should be set to ~/.cache in .config/profile.d/010-xdg-base-dirs.sh"
          elif [ ! "${XDG_CACHE_HOME}" == "${HOME}/.cache" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CACHE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_CACHE_HOME is set to \"${XDG_CACHE_HOME}\" but should be set to ~/.cache in .config/profile.d/010-xdg-base-dirs.sh"
          else
            echo "::notice file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CACHE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1)::XDG_CACHE_HOME is set correctly in .config/profile.d/010-xdg-base-dirs.sh"
          fi

          if [ -z "${XDG_DATA_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_DATA_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_DATA_HOME is not set but should be set to ~/.local/share in .config/profile.d/010-xdg-base-dirs.sh"
          elif [ ! "${XDG_DATA_HOME}" == "${HOME}/.local/share" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_DATA_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_DATA_HOME is set to \"${XDG_DATA_HOME}\" but should be set to ~/.local/share in .config/profile.d/010-xdg-base-dirs.sh"
          else
            echo "::notice file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_DATA_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1)::XDG_DATA_HOME is set correctly in .config/profile.d/010-xdg-base-dirs.sh"
          fi

          if [ -z "${XDG_STATE_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_STATE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_STATE_HOME is not set but should be set to ~/.local/state in .config/profile.d/010-xdg-base-dirs.sh"
          elif [ ! "${XDG_STATE_HOME}" == "${HOME}/.local/state" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_STATE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_STATE_HOME is set to \"${XDG_STATE_HOME}\" but should be set to ~/.local/state in .config/profile.d/010-xdg-base-dirs.sh"
          else
            echo "::notice file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_STATE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1)::XDG_STATE_HOME is set correctly in .config/profile.d/010-xdg-base-dirs.sh"
          fi
          echo "::endgroup::"

          echo "::group::Validate .config/profile.d/015-xdg-extra-dirs.sh"
          if [ -z "${XDG_BIN_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/015-xdg-extra-dirs.sh,line=$(awk '/XDG_BIN_HOME=/{print NR}' ~/.config/profile.d/015-xdg-extra-dirs.sh | head -n 1),title=ERROR::XDG_BIN_HOME is not set but should be set to ~/.local/bin in .config/profile.d/015-xdg-extra-dirs.sh"
          elif [ ! "${XDG_BIN_HOME}" == "${HOME}/.local/bin" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/015-xdg-extra-dirs.sh,line=$(awk '/XDG_BIN_HOME=/{print NR}' ~/.config/profile.d/015-xdg-extra-dirs.sh | head -n 1),title=ERROR::XDG_BIN_HOME is set to \"${XDG_BIN_HOME}\" but should be set to ~/.local/bin in .config/profile.d/015-xdg-extra-dirs.sh"
          else
            echo "::notice file=.config/profile.d/015-xdg-extra-dirs.sh,line=$(awk '/XDG_BIN_HOME=/{print NR}' ~/.config/profile.d/015-xdg-extra-dirs.sh | head -n 1)::XDG_BIN_HOME is set correctly in .config/profile.d/015-xdg-extra-dirs.sh"
          fi
          echo "::endgroup::"

          if [ -f "${errfile}" ]
          then
            echo "::error title=ERROR::Validation errors detected!"
            exit 1
          fi

  validate-zsh-environment:
    name: "Validate Zsh Environment"
    runs-on: macos-latest
    steps:

      - if: runner.debug == 1
        name: "Show zsh version"
        run: zsh --version

      - name: "Clone"
        run: git clone --bare https://github.com/norwd/etc ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - name: "Validate"
        shell: zsh -i -l {0}
        run: |
          errfile="${{ runner.temp }}/errfile.txt"

          echo "::group::Validate .zprofile"
          if [ -z ${SHELL_SESSIONS_DISABLE+x} ]
          then
            touch "${errfile}"
            echo "::error file=.zprofile,line=$(awk '/SHELL_SESSIONS_DISABLE/{print NR}' ~/.zprofile),title=ERROR::SHELL_SESSIONS_DISABLE is not set but should be set to 1 in .zprofile"
          else
            echo "::notice file=.zprofile,line=$(awk '/SHELL_SESSIONS_DISABLE/{print NR}' ~/.zprofile)::SHELL_SESSIONS_DISABLE is set correctly in .zprofile"
          fi
          echo "::endgroup::"

          echo "::group::Validate .config/profile.d/005-environment.sh"
          if [ -z "${VISUAL+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/005-environment.sh,line=$(awk '/VISUAL=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1),title=ERROR::VISUAL is not set but should be set to vim in .config/profile.d/005-environment.sh"
          elif [ ! "${VISUAL}" == "vim" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/005-environment.sh,line=$(awk '/VISUAL=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1),title=ERROR::VISUAL is set to \"${VISUAL}\" but should be set to vim in .config/profile.d/005-environment.sh"
          else
            echo "::notice file=.config/profile.d/005-environment.sh,line=$(awk '/VISUAL=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1)::VISUAL is set correctly in .config/profile.d/005-environment.sh"
          fi

          if [ -z "${EDITOR+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/005-environment.sh,line=$(awk '/EDITOR=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1),title=ERROR::EDITOR is not set but should be set to vim in .config/profile.d/005-environment.sh"
          elif [ ! "${EDITOR}" == "vim" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/005-environment.sh,line=$(awk '/EDITOR=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1),title=ERROR::EDITOR is set to \"${EDITOR}\" but should be set to vim in .config/profile.d/005-environment.sh"
          else
            echo "::notice file=.config/profile.d/005-environment.sh,line=$(awk '/EDITOR=/{print NR}' ~/.config/profile.d/005-environment.sh | head -n 1)::EDITOR is set correctly in .config/profile.d/005-environment.sh"
          fi
          echo "::endgroup::"

          echo "::group::Validate .config/profile.d/010-xdg-base-dirs.sh"
          if [ -z "${XDG_CONFIG_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CONFIG_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_CONFIG_HOME is not set but should be set to ~/.config in .config/profile.d/010-xdg-base-dirs.sh"
          elif [ ! "${XDG_CONFIG_HOME}" == "${HOME}/.config" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CONFIG_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_CONFIG_HOME is set to \"${XDG_CONFIG_HOME}\" but should be set to ~/.config in .config/profile.d/010-xdg-base-dirs.sh"
          else
            echo "::notice file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CONFIG_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1)::XDG_CONFIG_HOME is set correctly in .config/profile.d/010-xdg-base-dirs.sh"
          fi

          if [ -z "${XDG_CACHE_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CACHE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_CACHE_HOME is not set but should be set to ~/.cache in .config/profile.d/010-xdg-base-dirs.sh"
          elif [ ! "${XDG_CACHE_HOME}" == "${HOME}/.cache" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CACHE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_CACHE_HOME is set to \"${XDG_CACHE_HOME}\" but should be set to ~/.cache in .config/profile.d/010-xdg-base-dirs.sh"
          else
            echo "::notice file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_CACHE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1)::XDG_CACHE_HOME is set correctly in .config/profile.d/010-xdg-base-dirs.sh"
          fi

          if [ -z "${XDG_DATA_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_DATA_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_DATA_HOME is not set but should be set to ~/.local/share in .config/profile.d/010-xdg-base-dirs.sh"
          elif [ ! "${XDG_DATA_HOME}" == "${HOME}/.local/share" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_DATA_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_DATA_HOME is set to \"${XDG_DATA_HOME}\" but should be set to ~/.local/share in .config/profile.d/010-xdg-base-dirs.sh"
          else
            echo "::notice file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_DATA_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1)::XDG_DATA_HOME is set correctly in .config/profile.d/010-xdg-base-dirs.sh"
          fi

          if [ -z "${XDG_STATE_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_STATE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_STATE_HOME is not set but should be set to ~/.local/state in .config/profile.d/010-xdg-base-dirs.sh"
          elif [ ! "${XDG_STATE_HOME}" == "${HOME}/.local/state" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_STATE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1),title=ERROR::XDG_STATE_HOME is set to \"${XDG_STATE_HOME}\" but should be set to ~/.local/state in .config/profile.d/010-xdg-base-dirs.sh"
          else
            echo "::notice file=.config/profile.d/010-xdg-base-dirs.sh,line=$(awk '/XDG_STATE_HOME=/{print NR}' ~/.config/profile.d/010-xdg-base-dirs.sh | head -n 1)::XDG_STATE_HOME is set correctly in .config/profile.d/010-xdg-base-dirs.sh"
          fi
          echo "::endgroup::"

          echo "::group::Validate .config/profile.d/015-xdg-extra-dirs.sh"
          if [ -z "${XDG_BIN_HOME+x}" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/015-xdg-extra-dirs.sh,line=$(awk '/XDG_BIN_HOME=/{print NR}' ~/.config/profile.d/015-xdg-extra-dirs.sh | head -n 1),title=ERROR::XDG_BIN_HOME is not set but should be set to ~/.local/bin in .config/profile.d/015-xdg-extra-dirs.sh"
          elif [ ! "${XDG_BIN_HOME}" == "${HOME}/.local/bin" ]
          then
            touch "${errfile}"
            echo "::error file=.config/profile.d/015-xdg-extra-dirs.sh,line=$(awk '/XDG_BIN_HOME=/{print NR}' ~/.config/profile.d/015-xdg-extra-dirs.sh | head -n 1),title=ERROR::XDG_BIN_HOME is set to \"${XDG_BIN_HOME}\" but should be set to ~/.local/bin in .config/profile.d/015-xdg-extra-dirs.sh"
          else
            echo "::notice file=.config/profile.d/015-xdg-extra-dirs.sh,line=$(awk '/XDG_BIN_HOME=/{print NR}' ~/.config/profile.d/015-xdg-extra-dirs.sh | head -n 1)::XDG_BIN_HOME is set correctly in .config/profile.d/015-xdg-extra-dirs.sh"
          fi
          echo "::endgroup::"

          if [ -f "${errfile}" ]
          then
            echo "::error title=ERROR::Validation errors detected!"
            exit 1
          fi

  validate-zsh-options:
    name: "Validate Zsh Options"
    runs-on: macos-latest
    steps:

      - if: runner.debug == 1
        name: "Show zsh version"
        run: zsh --version

      - name: "Clone"
        run: git clone --bare https://github.com/norwd/etc ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - name: "Validate"
        shell: zsh -i -l {0}
        run: |
          errfile="${{ runner.temp }}/errfile.txt"

          for optname in \
            NOBEEP \
            CORRECTALL \
            CORRECT \
            DVORAK \
            AUTOCD \
            INCAPPENDHISTORY \
            SHAREHISTORY \
            COMPLETEALIASES \
            AUTOLIST \
            AUTOMENU
          do
            if [[ "$options[${optname}]" == "on" ]]
            then
              echo "::notice file=.zshrc,line=$(awk "/${optname}/{print NR}" ~/.zshrc | head -n 1)::${optname} is correctly set in .zshrc"
            else
              touch "${errfile}"
              echo "::error file=.zshrc,line=$(awk "/${optname}/{print NR}" ~/.zshrc | head -n 1),title=ERROR::${optname} should be set in .zshrc"
            fi
          done

          if [ -f "${errfile}" ]
          then
            echo "::error title=ERROR::Validation errors detected!"
            exit 1
          fi

  validate-vimrc:
    name: "Validate Vimrc"
    runs-on: macos-latest
    steps:

      - if: runner.debug == 1
        name: "Show vim version"
        run: vim --version

      - name: "Clone"
        run: git clone --bare https://github.com/norwd/etc ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - name: "Validate"
        run: |
          vim --cmd 'source ~/.config/vim/vimrc' --cmd 'echo &compatible' --cmd 'quit!' | hexdump

          errfile="${{ runner.temp }}/errfile.txt"

          # if [[ "$(vim --cmd 'source ~/.config/vim/vimrc' --cmd 'echo &compatible' --cmd 'quit!')" -eq 0 ]]
          # then
          #     echo "::notice file=.config/vim/vimrc,line=$(awk "/nocompatible/{print NR}" ~/.config/vim/vimrc | head -n 1)::nocompatible is correctly set in .config/vim/vimrc"
          # else
          #     echo "::error file=.config/vim/vimrc,line=$(awk "/nocompatible/{print NR}" ~/.config/vim/vimrc | head -n 1),title=ERROR::nocompatible should be set in .config/vim/vimrc"
          #     touch "${errfile}"
          # fi

          if [ -f "${errfile}" ]
          then
            echo "::error title=ERROR::Validation errors detected!"
            exit 1
          fi
