---

name: "Validate"
run-name: "Validate"
permissions: {}

on:
  schedule: [ cron: '33 9 * * 2' ]
  push:

jobs:

  validate-zsh-test-runner:
    name: "Validate with Zsh Test Runner"
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh -i -l {0}

    steps:

      - name: "Clone"
        run: git clone --bare ${{ github.server_url }}/${{ github.repository }} ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - name: "Install Zsh Test Runner"
        run: brew install olets/tap/zsh-test-runner

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test "${XDG_CONFIG_HOME}" = "${HOME}/.config"
          NAME: XDG_CONFIG_HOME is set to ~/.config
          NOTE: |
            The XDG_CONFIG_HOME must be set to ~/.config

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test -d "${XDG_CONFIG_HOME}"
          NAME: XDG_CONFIG_HOME is a dir
          NOTE: |
            The XDG_CONFIG_HOME must be a directory

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test "${XDG_CACHE_HOME}" = "${HOME}/.cache"
          NAME: XDG_CACHE_HOME is set to ~/.cache
          NOTE: |
            The XDG_CACHE_HOME must be set to ~/.cache

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test -d "${XDG_CACHE_HOME}"
          NAME: XDG_CACHE_HOME is a dir
          NOTE: |
            The XDG_CACHE_HOME must be a directory

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test "${XDG_DATA_HOME}" = "${HOME}/.local/share"
          NAME: XDG_DATA_HOME is set to ~/.local/share
          NOTE: |
            The XDG_DATA_HOME must be set to ~/.local/share

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test -d "${XDG_DATA_HOME}"
          NAME: XDG_DATA_HOME is a dir
          NOTE: |
            The XDG_DATA_HOME must be a directory

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test "${XDG_STATE_HOME}" = "${HOME}/.local/state"
          NAME: XDG_STATE_HOME is set to ~/.local/state
          NOTE: |
            The XDG_STATE_HOME must be set to ~/.local/state

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test -d "${XDG_STATE_HOME}"
          NAME: XDG_STATE_HOME is a dir
          NOTE: |
            The XDG_STATE_HOME must be a directory

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test "${XDG_BIN_HOME}" = "${HOME}/.local/bin"
          NAME: XDG_BIN_HOME is set to ~/.local/bin
          NOTE: |
            The XDG_BIN_HOME must be set to ~/.local/bin

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test -d "${XDG_BIN_HOME}"
          NAME: XDG_BIN_HOME is a dir
          NOTE: |
            The XDG_BIN_HOME must be a directory

      - name: "Ztr Test that ${{ env.NAME }}"
        run: ztr test "${TEST}" "${NAME}" "${NOTE}"
        env:
          TEST: test "$path[(Ie)$XDG_BIN_HOME]" -gt 0
          NAME: XDG_BIN_HOME is on the PATH
          NOTE: |
            The XDG_BIN_HOME must be in the PATH list

  validate-environment:
    name: "Validate Environment"
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh -i -l {0}

    steps:

      - name: "Clone"
        run: git clone --bare ${{ github.server_url }}/${{ github.repository }} ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - name: "Validate SHELL_SESSIONS_DISABLE"
        run: test "${SHELL_SESSIONS_DISABLE}" = "1"

      - name: "Validate VISUAL"
        run: test "${VISUAL}" = "vim"

      - name: "Validate EDITOR"
        run: test "${EDITOR}" = "vim"

  validate-zsh-options:
    name: "Validate Zsh Options"
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh -i -l {0}

    steps:

      - name: "Clone"
        run: git clone --bare ${{ github.server_url }}/${{ github.repository }} ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout -f

      - id: zsh-options
        name: "Dump Zsh Options"
        run: |
          for key value in ${(kv)options}
          do
            echo "${key}=$([[ "${value}" = "on" ]] && echo true || echo false)"
          done | sort | tee -a "${GITHUB_OUTPUT}"

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'aliases' option"
        run: ${{ fromJson(steps.zsh-options.outputs.aliases) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'appendhistory' option"
        run: ${{ fromJson(steps.zsh-options.outputs.appendhistory) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'autocd' option"
        run: ${{ fromJson(steps.zsh-options.outputs.autocd) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'autolist' option"
        run: ${{ fromJson(steps.zsh-options.outputs.autolist) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'automenu' option"
        run: ${{ fromJson(steps.zsh-options.outputs.automenu) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'beep' option"
        run: ${{ ! fromJson(steps.zsh-options.outputs.beep) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'completealiases' option"
        run: ${{ fromJson(steps.zsh-options.outputs.completealiases) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'correct' option"
        run: ${{ fromJson(steps.zsh-options.outputs.correct) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'correctall' option"
        run: ${{ fromJson(steps.zsh-options.outputs.correctall) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'dvorak' option"
        run: ${{ fromJson(steps.zsh-options.outputs.dvorak) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'incappendhistory' option"
        run: ${{ fromJson(steps.zsh-options.outputs.incappendhistory) || false }}

      - if: always() && steps.zsh-options.outcome == 'success'
        name: "Validate 'sharehistory' option"
        run: ${{ fromJson(steps.zsh-options.outputs.sharehistory) || false }}
