---

name: "Run ZUnit"
run-name: "Run ZUnit"
permissions: {}

on:
  push:
  schedule: [ cron: '33 9 * * 2' ]

jobs:
  zunit:
    name: "Run ZUnit"
    runs-on: macos-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Clone"
        run: git clone --bare ${{ github.server_url }}/${{ github.repository }} ~/etc

      - name: "Configure"
        run: git --git-dir="${HOME}/etc/" config --local status.showUntrackedFiles no

      - name: "Checkout"
        run: git --git-dir="${HOME}/etc/" --work-tree="${HOME}" checkout --force "${GITHUB_REF}"

      - name: "Install ZUnit"
        run: |
          # brew install zunit-zsh/zunit/zunit

          # Install revolver
          git clone https://github.com/molovo/revolver ${{ runner.temp }}/revolver
          cd ${{ runner.temp }}/revolver
          chmod u+x revolver/revolver
          mv revolver /usr/local/bin

          # Build ZUnit from source
          git clone https://github.com/zunit-zsh/zunit ${{ runner.temp }}/zunit
          cd ${{ runner.temp }}/zunit
          ./build.zsh

          # Copy zunit into $path
          cp zunit /usr/local/bin

      - name: "ZUnit Run Tests"
        run: zunit --verbose $(find . -type f -name "*.zunit")
