---

name: "Run ZUnit"
run-name: "Run ZUnit"
permissions: {}

on:
  push:
  schedule: [ cron: '33 9 * * 2' ]

jobs:
  zunit:
    name: "Run ZUnit"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Install revolver"
        run: |
          git clone https://github.com/molovo/revolver "${{ runner.temp }}/revolver"
          cd "${{ runner.temp }}/revolver"
          chmod u+x ./revolver
          cp ./revolver /usr/local/bin/

      - name: "Install ZUnit"
        run: |
          git clone https://github.com/zunit-zsh/zunit "${{ runner.temp }}/zunit"
          cd "${{ runner.temp }}/zunit"
          ./build.zsh
          chmod u+x ./zunit
          cp ./zunit /usr/local/bin/

      - name: "ZUnit Run Tests"
        shell: zunit {0}
        run: |
          #!/usr/bin/env zunit

          @test 'Example test' {
            assert 'true' same_as 'false'
          }

          @test 'Test XDG_CONFIG_HOME' {
            assert "${XDG_CONFIG_HOME}" same_as "${HOME}/.config"
            assert "${XDG_CONFIG_HOME}" is_dir
          }

          @test 'Test XDG_CACHE_HOME' {
            assert "${XDG_CACHE_HOME}" same_as "${HOME}/.cache"
            assert "${XDG_CACHE_HOME}" is_dir
          }

          @test 'Test XDG_DATA_HOME' {
            assert "${XDG_DATA_HOME}" same_as "${HOME}/.local/share"
            assert "${XDG_DATA_HOME}" is_dir
          }

          @test 'Test XDG_STATE_HOME' {
            assert "${XDG_STATE_HOME}" same_as "${HOME}/.local/state"
            assert "${XDG_STATE_HOME}" is_dir
          }

          @test 'Test XDG_BIN_HOME' {
            assert "${XDG_BIN_HOME}" same_as "${HOME}/.local/bin"
            assert "${XDG_BIN_HOME}" is_dir
            assert "$path[(Ie)$XDG_BIN_HOME]" is_greater_than 1
          }
